# the name of your event
name = "IPFS & WASM"

# the name of the group organizing the event
org = "PL Starfleet"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "@jbenet"

# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
website = "https://protocol.ai/labday"

# the start date of the event
date = "2022-07-15"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "09:00 - 17:00"

# the event venue name (will show up on the event card - TODO)
venueName = ""

# the event venue address (will show up on a map -- TODO)
venueAddress = ""

# the max number of attendees of the event
attendees = "50"


# these is unsued:
# tickets = "Waitlist"

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "All Welcome"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["WIP", "Talks", "Workshops"]

# a color, to group key events visually. use sparingly
# color="purple"

# a description of the track.
# will show up when the user clicks the event card.
#
# Notes:
# - use a markdown table for the schedule
# - recommended start: 09:00
# - recommended lunch: 12:00 or 13:00
# - recommended end:   17:00
# - use 15m, 20m, 30m, 45m, or 60m session slots
# - use 15m breaks, one in the morning, one or two in the afternoon
#
description = """

# IPFS and WASM track

Come and discuss how to imbue IPFS with WASM magical powers.

(?) - denotes tenative (not confirmed)

"""


[[timeslots]]
startTime="09:00"
speakers=[]
title="Welcome standup discussion"
description=""

[[timeslots]]
startTime="09:30"
speakers=[]
title="Track Intro"
description=""

[[timeslots]]
startTime="10:00"
speakers=[]
title="Open Slot"
description=""

[[timeslots]]
startTime="10:45"
speakers=["@raulk?"]
title="FVM Deep Dive"
description=""

[[timeslots]]
startTime="11:30"
speakers=["@stebalien?"]
title="WASM + IPLD"
description=""

[[timeslots]]
startTime="12:15"
speakers=[]
title="Lunch Break"
description=""

[[timeslots]]
startTime="13:00"
speakers=["@expede"]
title="IPVM"
description="Wasm modules, their arguments, intermediate states, their outputs, and managed effects can be described as IPLD graphs. IPVM is a strategy to support generalized deterministic computation in a serverless style on top of IPFS with optional sidechannel matchmaking on Filecoin, and extend the same benefits of shared data blocks to computation."

[[timeslots]]
startTime="13:30"
speakers=[]
title="Open Slot"
description=""

[[timeslots]]
startTime="14:00"
speakers=[]
title="Open Slot"
description=""

[[timeslots]]
startTime="14:30"
speakers=[]
title="Open Slot"
description=""

[[timeslots]]
startTime="15:00"
speakers=[]
title="Break"
description=""

[[timeslots]]
startTime="15:30"
speakers=[]
title="Open Slot"
description=""

[[timeslots]]
startTime="16:00"
speakers=[]
title="Open Slot"
description=""

[[timeslots]]
startTime="16:30"
speakers=[]
title="Open Slot"
description=""

[[timeslots]]
startTime="17:00"
speakers=[]
title="Open Slot"
description=""
